#!/bin/bash
###############################################################################
# FPCC wrapper
###############################################################################



function general_usage {
  echo "some general remarks and command list"
  exit 0
}

[[ $# -ge 1  ]] || general_usage

PREFIX=$(basename $0)
TOOL=$1
TOOL_EXEC="$0-${TOOL}"

# assert the tool exists as executable
[[ -x "${TOOL_EXEC}" ]] || general_usage

shift
exec -a "${PREFIX} ${TOOL}" "${TOOL_EXEC}" $@
