#!/bin/bash
###############################################################################
# FPCC wrapper
###############################################################################

PREFIX=$(basename $0)
TOOL=${1-help}
TOOL_EXEC="$(readlink -e $0)-${TOOL}"


# if the tool exists, invoke it
if [[ -x "${TOOL_EXEC}" ]]
then
  shift
  exec -a "${PREFIX} ${TOOL}" "${TOOL_EXEC}" $@
fi


# otherwise, try to invoke help
FPCC_HELP="$(readlink -e $0)-help"
[[ -x "${FPCC_HELP}" ]] && exec "${FPCC_HELP}"

# if we reach here, something is seriously broken
echo "No "$(basename "${FPCC_HELP}")" found. " \
  "Your fpcc installation seems to be broken." 2>&1
exit 1
